export type Colors =
  | 'bg/dark'
  | 'bg/light'
  | 'bg/grey/1'
  | 'bg/grey/2'
  | 'bg/grey/3'
  | 'bg/blue/1'
  | 'blue/1'
  | 'blue/2'
  | 'text/button/contained'
  | 'text/button/outlined'
  | 'text/button/ghost'
  | 'text/black/1'
  | 'text/grey/1'
  | 'text/disabled'
  | 'text/error'
  | 'text/success'
  | 'button/default'
  | 'button/hover'
  | 'button/pressed'
  | 'button/disabled'
  | 'stroke/default'
  | 'stroke/hover'
  | 'stroke/pressed'
  | 'stroke/disabled'
  | 'field/default'
  | 'field/focused'
  | 'field/disabled'
  | 'field/error'
  | 'field/success';

export const defaultColors: Record<Colors, string> = {
  'bg/dark': '#FFFFFF',
  'bg/light': '#001054',
  'bg/grey/1': '#EFEFF2',
  'bg/grey/2': '#FAFAFF',
  'bg/grey/3': '#F0F0F5',
  'bg/blue/1': '#D9F2FF',
  'blue/1': '#5770D1',
  'blue/2': '#5FBEF7',
  'text/button/contained': '#F1F3F3',
  'text/button/outlined': '#5770D1',
  'text/button/ghost': '#5770D1',
  'text/black/1': '#000027',
  'text/grey/1': '#5A5A81',
  'text/disabled': '#B4B4DB',
  'text/error': '#BD0000',
  'text/success': '#51BA82',
  'button/default': '#5770D1',
  'button/hover': '#435CBD',
  'button/pressed': '#2F48A9',
  'button/disabled': '#E6E6FF',
  'stroke/default': '#5770D1',
  'stroke/hover': '#4D66C7',
  'stroke/pressed': '#2F48A9',
  'stroke/disabled': '#F1F3F3',
  'field/default': '#D9F2FF',
  'field/focused': '#CFE8F5',
  'field/disabled': '#F1F3F3',
  'field/error': '#BD0000',
  'field/success': '#51BA82',
};
